Features/categories
mathisang/hackaton-grp3 pull request #18
Opened 2023-07-19 21:13 UTC by mathisang

2023-07-19 21:15 UTC, JulienDupontDev requested changes

2023-07-19 21:15 UTC, JulienDupontDev commented on src/components/DateHeader/DateHeader.js
> +  // useEffect(() => {
Remets ça enlève la dépendance sur today. 

Ne pas afficher l'heure dans le bloc de date

2023-07-19 21:16 UTC, JulienDupontDev requested changes
Il manque le titre de la page

2023-07-20 07:51 UTC, Sharcan approved these changes

2023-07-20 07:56 UTC, JulienDupontDev approved these changes

2023-07-20 07:56 UTC, merged